theme = "rose_pine_moon"
client_port = 8080
client_id = "eda1c2faa4874f47a8ff8a55a0abb6f7"
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists} {liked}
{album} • {genres}
{metadata}"""
playback_metadata_fields = [
    "repeat",
    "shuffle",
    "volume",
    "device",
]
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
# pause_icon = "▌▌"
pause_icon = ""
liked_icon = "󰋑"
border_type = "Plain"
progress_bar_type = "Rectangle"
progress_bar_position = "Bottom"
genre_num = 3
enable_media_control = true
enable_streaming = "Always"
enable_notify = true
enable_cover_image_cache = true
cover_img_width = 10
cover_img_length = 20
cover_img_pixels = 64
default_device = "spotify-player"
notify_streaming_only = true
seek_duration_secs = 5
sort_artist_albums_by_type = false

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[layout]
playback_window_position = "Bottom"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = true
normalization = false
autoplay = false
